apiVersion: v1
kind: Service
metadata:
  name: enterprise-system-20260526-224626-hvun33sjmdzi-service
spec:
  selector:
    app: enterprise-system-20260526-224626-hvun33sjmdzi
  ports:
  - port: 80
    targetPort: 8000
  type: ClusterIP
